/work/scratch/kurse/kurs00079/data/vox2/shared_code/Project-Lab-MAI/AdaFace/inference.py:18: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  statedict = torch.load(adaface_models[architecture])["state_dict"]
/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/whisper/__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
Starting training...

Epoch 1/10
Traceback (most recent call last):                                                                                                                                                                                                                                                            
An error occurred: module 'av' has no attribute 'AVError'
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/torchvision/io/video.py", line 420, in read_video_timestamps
    with av.open(filename, metadata_errors="ignore") as container:
  File "av/container/core.pyx", line 369, in av.container.core.open
  File "av/container/core.pyx", line 236, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 256, in av.container.core.Container.err_check
  File "av/error.pyx", line 428, in av.error.err_check
av.error.ProtocolNotFoundError: [Errno 1330794744] Protocol not found: 'E:\\MAI Dataset/dev/mp4/id07005/CyLFnxpzklI/00127.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/scratch/kurse/kurs00079/data/vox2/shared_code/Project-Lab-MAI/train_crossmodal.py", line 260, in <module>
    main()
  File "/work/scratch/kurse/kurs00079/data/vox2/shared_code/Project-Lab-MAI/train_crossmodal.py", line 205, in main
    train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
  File "/work/scratch/kurse/kurs00079/data/vox2/shared_code/Project-Lab-MAI/train_crossmodal.py", line 38, in train_epoch
    for batch in progress_bar:
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work/scratch/kurse/kurs00079/data/vox2/shared_code/Project-Lab-MAI/crossmodal_training.py", line 420, in __getitem__
    frames, frame_times, audio, info = self._load_video_frames(video_path)
  File "/work/scratch/kurse/kurs00079/data/vox2/shared_code/Project-Lab-MAI/crossmodal_training.py", line 391, in _load_video_frames
    pts, fps = read_video_timestamps(str(video_path))
  File "/work/home/og70qiri/MAI/MAI/lib/python3.9/site-packages/torchvision/io/video.py", line 429, in read_video_timestamps
    except av.AVError as e:
AttributeError: module 'av' has no attribute 'AVError'
